language: python
before_install:
  - pip install pytest pytest-cov httpretty coveralls
install:
  - pip install .
  - pip install -r requirements.txt
script:
  - py.test --cov=sigep --cov-config .coveragerc -v --color=yes --showlocals tests/
after_success:
  - coveralls